const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const listeners = {}, frames = [], storage = new Map();
const location = { hash: '#colecao/game' };
const context = { location, sessionStorage: { getItem: key => storage.get(key), setItem: (key, value) => storage.set(key, value) }, setTimeout };
context.window = { scrollY: 840, addEventListener: (name, fn) => listeners[name] = fn, requestAnimationFrame: fn => frames.push(fn), scrollTo: ({top}) => { context.window.scrollY = top; } };
vm.runInNewContext(fs.readFileSync('dist/navigation.js', 'utf8'), context);
context.window.Navigation.capture();
location.hash = '#titulo/game/local'; listeners.hashchange();
context.window.scrollY = 640; listeners.scroll(); context.window.Navigation.restore();
while(frames.length) frames.shift()();
assert.equal(context.window.scrollY, 0);
context.window.scrollY = 320; listeners.scroll();
location.hash = '#colecao/game'; listeners.hashchange(); frames.shift()(); frames.shift()();
assert.equal(context.window.scrollY, 840);
context.window.Navigation.restore('#titulo/game/local');
assert.equal(frames.length, 0, 'Uma página obsoleta não agenda restauração');
assert.equal(context.window.scrollY, 840, 'Uma restauração atrasada não deve mover outra página');
assert.equal(JSON.parse(storage.get('myspace-reading-positions')).length, 2);
console.log('Posição por página, retorno e proteção contra restauração atrasada OK.');
